### ISSUE TITLE
can I use it on ES5 ?

### ISSUE THREAD

**Issue by baram204** [sindresorhus/on-change#13]
I want to use it ES5 on IE11.

**Comment by ArfatSalman** [comment]
IE11 does not support ES6 proxies. Also, if you try to convert ES6 proxies to ES5 using babel, babel will not transpile proxy code. However, for limited features, you may  checkout this proxy [polyfill](https://github.com/GoogleChrome/proxy-polyfill).

According to the [Babel docs ](https://babeljs.io/docs/en/learn/#ecmascript-2015-features-proxies)

> Due to the limitations of ES5, Proxies cannot be transpiled or polyfilled. See support in various JavaScript engines.
