### ISSUE TITLE
Will this work with a polyfill?

### ISSUE THREAD

**Issue by KhaledElAnsari** [sindresorhus/on-change#2]
I'm curious if it will work with some polyfill, polyfilling proxy is almost impossible only [this polyfill](https://github.com/GoogleChrome/proxy-polyfill) is somehow doing the minimal job of a proxy

Is it possible to rely on methods like `get` and `set` to make this module cover more browsers or it will kill the purpose on it?

**Comment by sindresorhus** [comment]
No idea, and honestly not something I care about. This module targets Node.js 6 and up. If you want it in the browser it's up to you to figure out whether it will work or not in the browsers you want to support :)

**Comment by KhaledElAnsari** [comment]
at least write that in the README!!!
