### ISSUE TITLE
Array change within object loses callback details

### ISSUE THREAD

**Issue by jmquigley** [sindresorhus/on-change#24]
test.ts
```ts
const onChange = require("on-change");

let i: number = 0;
const obj = {
    a: "",
    b: ["a", "b", "c"]
};

const watchedSettings = onChange(obj, function(
    path: any,
    value: any,
    previousValue: any
) {
    console.log("Object changed:", ++i);
    console.log("this:", this);
    console.log("path:", path);
    console.log("value:", value);
    console.log("previousValue:", previousValue);
});

watchedSettings.a = "test";
watchedSettings.b.push("d");
```

The output from this is:

```
~>tsc -p . && node test.js
Object changed: 1
this: { a: 'test', b: [ 'a', 'b', 'c' ] }
path: a
value: test
previousValue:
Object changed: 2
this: undefined
path: undefined
value: undefined
previousValue: undefined
```

The change to "a" works, but the update to the array "b" in the second returns "undefined" for all fields in the callback.  It detected the change, but lost all of the details.

node: 11.12.0
on-change: 1.2.0
typescript: 3.4.1

**Comment by sindresorhus** [comment]
// @DarrenPaulWright

**Comment by DarrenPaulWright** [comment]
Is it only when you push to the array? Have you noticed any other scenarios (like shift, unshift, pop, or direct setting of items in the array) that cause this behavior? I should be able to look into this more later today.

**Comment by jmquigley** [comment]
I was only working with an array at the time.  I modified the sample above to do push, unshift, pop, and direct manipulation.  The only one that worked as expected was direct manipulation.   I'm working around this right now by cloning the array, modifying it, and then adding it back to the attribute on the object (not editing the array in place, shown in the sample below).

```javascript
import {clone} from "lodash";

const onChange = require("on-change");

let i: number = 0;
const obj = {
    a: "",
    b: ["a", "b", "c"]
};

const watchedSettings = onChange(obj, function(
    path: any,
    value: any,
    previousValue: any
) {
    console.log("Object changed:", ++i);
    console.log("this:", this);
    console.log("path:", path);
    console.log("value:", value);
    console.log("previousValue:", previousValue);
});

watchedSettings.a = "test";     // 1
watchedSettings.b.push("d");    // 2
watchedSettings.b.unshift("e"); // 3
watchedSettings.b.pop();        // 4
watchedSettings.b[0] = "foo";   // 5

// workaround

const tmp = clone(watchedSettings.b);
tmp.push("f");
watchedSettings.b = tmp;        // 6
```

The output:

```
~>tsc -p . && node test.js
Object changed: 1
this: { a: 'test', b: [ 'a', 'b', 'c' ] }
path: a
value: test
previousValue:
Object changed: 2
this: undefined
path: undefined
value: undefined
previousValue: undefined
Object changed: 3
this: undefined
path: undefined
value: undefined
previousValue: undefined
Object changed: 4
this: undefined
path: undefined
value: undefined
previousValue: undefined
Object changed: 5
this: { a: 'test', b: [ 'foo', 'a', 'b', 'c' ] }
path: b.0
value: foo
previousValue: e
Object changed: 6
this: { a: 'test', b: [ 'foo', 'a', 'b', 'c', 'f' ] }
path: b
value: [ 'foo', 'a', 'b', 'c', 'f' ]
previousValue: [ 'foo', 'a', 'b', 'c' ]
```

**Comment by DarrenPaulWright** [comment]
@sindresorhus @kpruden 
Ok, so I found the problem, but I have questions. For push and pop the solution is fairly straight forward, I can return information for that index. But for shift, unshift, concat, or forEach, it gets more complicated. What would you expect to see if you unshift an item to the beginning of an array? Technically all the items in the array have changed index, so should I just return that the array has changed and provide the new array and previous array? Or would it be sufficient to say that the first item changed with a previous value of undefined? For concat and forEach, multiple items may have changed, so do we need a way of specifying exactly which items changed, or a range of items, or again can we just say that the array changed? I'd appreciate feedback before I implement a solution.
