### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by felixfbecker** [sindresorhus/on-change#3]
I am curious about the performance of this vs. calling `save` explicitly. Is there a benchmark?

**Comment by sindresorhus** [comment]
No benchmark yet. I plan to add it eventually but won't be very soon as I have a lot of things to deal with right now. The Proxy API have gotten a lot faster in the latest V8 though: https://v8project.blogspot.no/2017/10/optimizing-proxies.html

**Comment by ashu17706** [comment]
@sindresorhus Can I work on it.
If you can guide me to start. I understand JS proxy little bit.

**Comment by sindresorhus** [comment]
@ashu17706 Awesome! You can see how to add the benchmarking stuff here: https://github.com/sindresorhus/camelcase-keys/commit/5d6421aedf96733b9fa4792182f4db56782388c6

**Comment by glundgren93** [comment]
In this case, save is just a normal function, right?

**Comment by sindresorhus** [comment]
Yes
