### ISSUE TITLE
Enhancement: The callback is not called when class methods set properties

### ISSUE THREAD

**Issue by mjstahl** [sindresorhus/on-change#33]
```js
class Counter {
  constructor () {
    setInterval(this.onTick.bind(this), 1000)
  }
  onTick () {
    // the setting of hours, minutes, seconds does not call the callback
    const now = new Date()
    this.hours = now.getHours()
    this.minutes = now.getMinutes()
    this.seconds = now.getSeconds()
  }
}
var counter = onchange(new Counter(), (property, value) => {
  console.log(property, value)
})
```

The callback will be called if I do:

```js
counter.title = 'CLOCK'
```

This makes sense, because `this` referenced in `onTick` is not the Proxy but the instance of `Counter`. Not completely sure what the correct solution is here. Use of the `constructor` trap?

**Comment by DarrenPaulWright** [comment]
I'm thinking an option that re-binds all methods to the proxied object may do what you want. And I can definitely see the value of something like that. I'll play around with it and let you know.

**Comment by mjstahl** [comment]
I just tried it in my own package (https://github.com/elementreejs/elementree/blob/4ccb01182c9fd560b42fbac0a62f6e797e13f9e9/create.js#L31) but so far no luck. The example above still doesn't work. 

Then again, I am not sure what I should be binding to what. First I was binding the instance to the proxy. But I realized, I really should be binding the proxy methods to the proxy. 

Neither worked. So not entirely sure just yet.

**Comment by DarrenPaulWright** [comment]
This should be fixed by 2c8d1e0e4fceca3c4c3ad0add0b01650d2f2c6fa, though you will only get one callback after the entire method is done executing. If you need to get callbacks for each property change within a method call, let me know.

**Comment by mjstahl** [comment]
new release going out? It's not a big deal I can still test it all out with the commit hash.

**Comment by DarrenPaulWright** [comment]
@sindresorhus I think we're ready for a minor version bump.

**Comment by DarrenPaulWright** [comment]
Thanks @mjstahl !

**Comment by mjstahl** [comment]
No thank you @DarrenPaulWright =)

**Comment by sindresorhus** [comment]
> @sindresorhus I think we're ready for a minor version bump.

Done
