### ISSUE TITLE
Strange behavior when using onChange in a constructor

### ISSUE THREAD

**Issue by ChuckFields** [sindresorhus/on-change#36]
I've made a small example to show this:
[https://codesandbox.io/s/vigorous-volhard-f1ox5](https://codesandbox.io/s/vigorous-volhard-f1ox5)

I can declare a new Address object and it ends up being a proxy because it extends AbstractProxiedObject which uses onChange, however, if I assign it to the property 'address' on a Person in the Person constructor, it's no longer a proxy. 

I was able to trace this back to line 112 of index.js
If I return 'receiver' instead of 'target' in the 'get' function, my example works just fine.
So the question becomes, should we be returning 'receiver' in 'get'? Or is there something i'm doing wrong in my code?

It's also worth mentioning that if I remove 'extends AbstractProxiedObject' from the Person object, my example works just fine as well - which is a bit of a head scratcher... are the person and address objects interfering with each other somehow?

Any incite into this problem would be much appreciated.

**Comment by DarrenPaulWright** [comment]
Fixed by 226f20470a9c7b43ad849edd70594aa7ca3b06fe
