### ISSUE TITLE
Unsubscribe 

### ISSUE THREAD

**Issue by linonetwo** [sindresorhus/on-change#38]
Hope I can unsubscribe to change, so this can be used in React hook, for example, useEffct, which ask you to return an unsubscription function.

**Comment by DarrenPaulWright** [comment]
I don't know of a way to unsubscribe right now. I'll look into it.

**Comment by cbbfcd** [comment]
if we keep the raw target with a variable like `originalTarget`，and provide a unsubscribe function, when the function be invoked, we let proxy revoke and replace the return obj with originalTarget??

**Comment by DarrenPaulWright** [comment]
@linonetwo How do other react libraries handle this? If you could call something like proxiedObject['[[target]]'] to get the original target, would that be sufficient? Or do you need a way to stop all further callbacks on the proxied object?

**Comment by linonetwo** [comment]
I think unsubscribe can be something like:

```js
watchedObject[SymbolUnsubscribe] // [Function]
```

And react hook user can use it like:

```
function SomeReactComponent(props) {
const obj = useRef();
useEffect(() => {
	const watchedObject = onChange(object, () => {});
	obj.current = watchedObject;
	return watchedObject[SymbolUnsubscribe];
}, [props.obj])
return <><ChildComponent obj={obj} /></>
}
```

Do you think it is reasonable?

**Comment by DarrenPaulWright** [comment]
Would this do the same thing?
``` javascript
function SomeReactComponent(props) {
const obj = useRef();
useEffect(() => {
	const original = {};
	obj.current = onChange(original, () => {});
	return original;
}, [props.obj])
return <><ChildComponent obj={obj} /></>
}
```
either way, you're still creating a new onChange proxy every time `useEffect` is called.

What do you want to happen when the object changes?

**Comment by linonetwo** [comment]
I know what you mean. Maybe just replace `ref.current` with a new proxyed object, and letting old one to be GC.

```jsx
function SomeReactComponent(props) {
const obj = useRef();
useEffect(() => {
	const original = {};
	obj.current = onChange(original, () => {});
}, [props.obj])
return <><ChildComponent obj={obj} /></>
}
```

Normally subscription won't be easily GC, for example, socket subscription, so we need to return an unsubscription function. But in this case, we might not need to.

Thank you for answering.

**Comment by DarrenPaulWright** [comment]
@linonetwo unsubscribe is now supported:
``` js
onChange.unsubscribe(watchedObject);
```

**Comment by linonetwo** [comment]
Cool, thank you for that.
