### ISSUE TITLE
Listen on original object change instead of return a new one

### ISSUE THREAD

**Issue by linonetwo** [sindresorhus/on-change#39]
I got an object that its internal value is changed by another library (I'm writing a binding from it to React), and internal value change won't trigger React rerender. So I need to monitor **the original object**'s internal change and trigger rerender by hand.

**Comment by DarrenPaulWright** [comment]
I don't know of a way to do what you want. I don't think Proxies work that way. Could you recommend to the other library to use on-change to give you the functionality you need?

**Comment by linonetwo** [comment]
Actually, I found it unachievable.

My original object is actually doing [transient updates](https://github.com/drcmda/react-three-fiber/issues/61#issuecomment-504472284), I was hoping I can rerender react component upon update. But I finally found that it is better no to rerender react component. Instead, check that object's internal value on a `requestAnimationFrame` and perform an imperative update is more performance.
