### ISSUE TITLE
Methods that return new objects (.map, .filter) should be proxied as well.

### ISSUE THREAD

**Issue by mjstahl** [sindresorhus/on-change#40]
```js
const proxied = onChange([1, 2, 3], function () { ... })
const notProxied = proxied.filter(x => x > 1)
```

I think we might have to use [Symbol.species](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/species) but not completely sure yet.

**Comment by mjstahl** [comment]
I tried this out in a repl, and seems to work nicely. I am not sure how integrate these ideas generically.

```js
class ProxiedArray extends Array {
    static get [Symbol.species]() {
        return proxy // the proxy created around 219
    }
}
```

**Comment by DarrenPaulWright** [comment]
The new object that is returned is just that, a _new_ object. If you modify the new object, then 
you are _not_ modifying the target object, so I would not expect the callback to be called. 

Can you provide a use case for what your asking?

**Comment by mjstahl** [comment]
Oh sure. It might be out of scope, but I figured I would bring it up to see what other's thought.

```js
import onChange from 'on-change'

const listOf = [1, 2, 3, 4]
const proxied = onChange(listOf, function () { ... })

// or splice, map, or any other Array.prototype function that returns a new Array
const filtered = proxied.filter(() => { ... })
```

The use case is `filtered` being a Proxy with the same "callback" as `proxied`.
