### ISSUE TITLE
Path should be an array

### ISSUE THREAD

**Issue by qwelias** [sindresorhus/on-change#44]
Path arg should be an array, since prop name could contain `.`

**Comment by kevva** [comment]
I'd rather return an escaped path like `foo.foo\\.bar` which corresponds to `{foo: {'foo.bar': true}}`.

**Comment by qwelias** [comment]
@kevva 
Popular where?
If in mongodb? Yes, because they prohibit for as a key.
If in lodash? They allow for array for compatibility with dot in props.

An if you return "escaped" dots, how should consumer process the string? Will you include a function for unescaping too?

**Comment by kevva** [comment]
Well, it's how you write it when accessing props on an object for example. You can parse it using https://github.com/sindresorhus/dot-prop.

**Comment by qwelias** [comment]
@kevva so would I have to install that package too to use this one? This is ridiculous

**Comment by kevva** [comment]
No, it's just a suggestion. You'd still have to convert the array to something before you could access the property of the object as well so I don't see what the tradeoff is here.

**Comment by qwelias** [comment]
@kevva 
The tradeoff is that if given
```js
{
  'a.b':1,
  'a': { 'b': 2 },
}
```
Changing 1 or 2 in case of array would produce determined `path` (`['a', 'b']` or `['a.b']` repectively), while using string would produce `'a.b'` in both cases. And if you escape '.' with anything you'd have to split the string into valid array of props before unescaping where it was escaped as you suggested.

Also, considering, that implementation relies on dotted path in `walkPath` funciton there could be related bugs if props have dots in their names.

The point is, **you cannot use dot as an object-tree path separator since it's a valid character for property names**.

That's the reason popular utility libs use primarily array as object-tree path, string only as a convenience option. Look at `lodash` or `ramda`.

**Comment by kevva** [comment]
I'm not saying that I disregard your solution, I just prefer the escaped one. It's non-breaking (most likely) and is directly compatible with [`dot-prop`](https://github.com/sindresorhus/dot-prop).

> Also, considering, that implementation relies on dotted path in walkPath funciton there could be related bugs if props have dots in their names.

This is a non-issue IMO. It's easy to check for in code providing that the path is escaped. But yeah, I'm not opposed to returning `path` as an array either.

**Comment by qwelias** [comment]
I think I'll start working on PR in spare time
