### ISSUE TITLE
Call the callback when setting a new property to undefined

### ISSUE THREAD

**Issue by fabiospampinato** [sindresorhus/on-change#46]
I think there's a bug here:

https://github.com/sindresorhus/on-change/blob/5a9b0f8cfd9ffd27baa77020215929a2e2884fc6/index.js#L190

The previous and new value can be the same if we are setting `undefined` and the property wasn't set before, but in that case this would still be a mutation as we are adding a new property to the object.

**Comment by DarrenPaulWright** [comment]
Another interesting one. Same as my other response, pull requests are welcome, otherwise I'll handle it soon.

**Comment by DarrenPaulWright** [comment]
Fixed in 1.6.3
