### ISSUE TITLE
Don't trigger the callback if the operation fails

### ISSUE THREAD

**Issue by fabiospampinato** [sindresorhus/on-change#47]
Here:

https://github.com/sindresorhus/on-change/blob/5a9b0f8cfd9ffd27baa77020215929a2e2884fc6/index.js#L190

We are not accounting for the return value of `Reflect.set` when deciding whether to trigger the callback or not, but if `Reflect.set` returns false then the set operation failed (maybe the object wasn't writable, maybe the setter threw an error etc.) so nothing actually changed and the callback shouldn't be called.

I think the `defineProperty` and `deleteProperty` traps are also affected by this issue.

**Comment by DarrenPaulWright** [comment]
Good catch. I'm in the middle of something else at the moment, so I probably won't be able to address this directly for a few days. I'f you're up for submitting a pull request that would be great, otherwise I'll get to it as soon as i can.

**Comment by DarrenPaulWright** [comment]
Fixed in 1.6.3
