### ISSUE TITLE
Improve "apply" trap performance

### ISSUE THREAD

**Issue by fabiospampinato** [sindresorhus/on-change#48]
I'm kind of rewriting this library to better suit my needs and I think I've found an interesting performance optimization.

Some methods of builtin objects can't mutate the object in question, like for instance calling `forEach` on an Array will never mutate the array, so we can avoid [cloning](https://github.com/sindresorhus/on-change/blob/5a9b0f8cfd9ffd27baa77020215929a2e2884fc6/index.js#L242), performing potentially expensive equality checks comparisons etc.

This is assuming the prototype of Array doesn't get messed up with, but IMHO if somebody changes it in a way that non-mutating methods become mutating it's on them.

**Comment by fabiospampinato** [comment]
Actually those methods don't need to be proxied in the first place, in my benchmarks this improves performance 10x.

**Comment by fabiospampinato** [comment]
> Actually those methods don't need to be proxied in the first place, in my benchmarks this improves performance 10x.

Actually some of those methods need to be proxied, as otherwise for example mutating an object retrieved via `forEach` won't be recognized as a change.

This is still a ~4x performance improvement according to my benchmarks though.

**Comment by DarrenPaulWright** [comment]
> > Actually those methods don't need to be proxied in the first place, in my benchmarks this improves performance 10x.
> 
> Actually some of those methods need to be proxied, as otherwise for example mutating an object retrieved via forEach won't be recognized as a change.
>
> This is still a ~4x performance improvement according to my benchmarks though.

Are you just whitelisting specific methods? Pull requests are welcome :)

**Comment by fabiospampinato** [comment]
> Are you just whitelisting specific methods?

Essentially, yeah. [Here's](https://github.com/fabiospampinato/proxy-watcher/blob/1e5d6a75b522679191e1ffd7f3d11be422e8963d/src/consts.ts#L10-L82) the list.

I'm cutting corners a bit by not even checking what kind of objects have those methods, I'll see how that goes.

> Pull requests are welcome :)

Thanks but as I basically ended up rewriting the entire thing (in hindsight I probably could have just forked this and submitted a bunch of PRs, but one of the main features I wanted my library to have in the end I couldn't implement) I won't really use `on-change` so I don't want to kind of help maintaining it too.

**Comment by DarrenPaulWright** [comment]
Added in 2.1.0
