### ISSUE TITLE
defineProperty doesn't check for equality

### ISSUE THREAD

**Issue by fabiospampinato** [sindresorhus/on-change#49]
I think there's a problem here:

https://github.com/sindresorhus/on-change/blob/5a9b0f8cfd9ffd27baa77020215929a2e2884fc6/index.js#L198

Each `defineProperty` call is basically counted as a change, even if the property descriptor is exactly the same, I think the current and the next descriptor need to be compared before triggering a change.

**Comment by DarrenPaulWright** [comment]
Fixed in 1.6.3
