### ISSUE TITLE
Not detecting underlying field changes in javascript setter

### ISSUE THREAD

**Issue by ChuckFields** [sindresorhus/on-change#50]
If I have a setter function on an object that modifies a 'private' field, on-change will only pick up a change on the setter field, not the underlying 'private' field. Take a look at [this example](https://codesandbox.io/s/twilight-monad-zqr9s).

I have a setter called 'something' that modifies a field called '_something'. propChanged gets called for 'something' but not for '_something'. I would think it should get called for both.

**Comment by DarrenPaulWright** [comment]
You appear to be correct. I'll look into it. Thanks for the helpful example!

**Comment by ChuckFields** [comment]
@DarrenPaulWright  I figured out the underlying problem, but I can't seem to come up with an elegant solution. The problem is, inside of a javascript setter, 'this' is not the proxied object but rather the original object- which explains why _something did not trigger propChanged(). This can be seen in [this example](https://codesandbox.io/s/bold-brattain-fd8qf). Note: codesandbox.io seems to have some weird issues with proxies so only use that link to see the code. You can use their embedded address bar link and see the output in your browsers console: [https://fd8qf.csb.app/](https://fd8qf.csb.app/). You can see my attempt at a solution is to tack on $proxiedObject to the original object which can be accessed in the setter. I don't particularly like this solution because it creates a circular reference. Do you have any ideas for a better solution?

**Comment by DarrenPaulWright** [comment]
I was working on a solution a few weeks ago, but I had to pause so I could move half-way across the US. I'll try to wrap it up in the next few days.

**Comment by DarrenPaulWright** [comment]
Fixed in 2.0.2
