### ISSUE TITLE
Stop watching object once it is removed

### ISSUE THREAD

**Issue by gurupras** [sindresorhus/on-change#58]
I've been trying to build a tiny library for app-server configs that can dynamically update sub-components when a part of the config changes. While testing this, I ran into an issue where the object being monitored by `onChange` would react to changes even though that part of the object was already replaced.

Here's a [pen](https://codepen.io/gurupras/pen/jObrZBJ) that reproduces this issue. Here's a small snippet to reproduce it that you can just paste into a `.js` file and run

```
const onChange = require('on-change')

const config = {
  server: {
    dev: {
      host: 'dev-host',
      port: 30
    }
  }
}

const proxy = onChange(config, (path, v, o) => {
  console.log(`path=${path} from=${JSON.stringify(o)} to=${JSON.stringify(v)}`)
})

const old = proxy.server.dev
proxy.server.dev = { host: 'new-dev-host', port: 60 }
// Now, change the old object
old.host = 'bad'
```

**Comment by DarrenPaulWright** [comment]
Until I get a solution built, you can try calling `onChange.unsubscribe(o)` inside the onChange callback to stop watching the old object. Your const `old` will still be proxied, but it should stop triggering the onChange callback.

**Comment by DarrenPaulWright** [comment]
I added an option 'ignoreDetached' to 2.2.0 that should fix this issue. Let me know if you have any problems.
