### ISSUE TITLE
Not just pass the name to the listener but also the arguments

### ISSUE THREAD

**Issue by Eluminati** [sindresorhus/on-change#62]
Hi there,

I am very very hapy about the last update. With the additional information, which method was used on the array, you can do much more things with this lib. But it turned out that it can be very hard to determine what happened exactly to an array. For example splice. Currently I am doing much things to determine which elements are added and which are removed. Example:

```javascript
if (name === "splice") {
    const calcPrevVal = [];
    const calcChangedVal = []
    let startIndex = 0;
    let endIndex = 0
    let startFound = false;
    let endFound = false
    for (let index = 0; index < Math.max(changedVal.length, prevVal.length); index++) {
        const indexToUseFromBehind = prevVal.length >= changedVal.length ? prevVal.length - (1 + index) : changedVal.length - (1 + index);
        const lastPrevVal = prevVal.length - (1 + index) >= 0 ? prevVal[prevVal.length - (1 + index)] : undefined;
        const lastChangedVal = changedVal.length - (1 + index) >= 0 ? changedVal[changedVal.length - (1 + index)] : undefined
        if (!endFound) {
            if (lastChangedVal !== lastPrevVal) {
                endIndex = indexToUseFromBehind;
                endFound = true;
            } else {
                calcChangedVal[indexToUseFromBehind] = lastChangedVal;
                calcPrevVal[indexToUseFromBehind] = lastPrevVal;
            }
        
        if (!startFound) {
            if (prevVal[index] !== changedVal[index]) {
                startIndex = index;
                startFound = true;
            } else {
                calcChangedVal[index] = changedVal[index];
                calcPrevVal[index] = prevVal[index];
            }
        
        if (startFound && endFound) {
            for (let index = startIndex; index <= endIndex + (changedVal.length - prevVal.length); index++) {
                calcChangedVal[index] = changedVal[index];
            }
            for (let index = startIndex; index <= endIndex + (prevVal.length - changedVal.length) + (prevVal.length >= changedVal.length ? 1 : 0); index++) {
                calcPrevVal[index] = prevVal[index];
            }
            for (let index = startIndex; index < endIndex + 1; index++) {
                const prevElement = calcPrevVal[index];
                const changedElement = calcChangedVal[index];
                if (prevElement) {
                    Object.assign(removedElements, { [index]: prevElement });
                    if (changedElement) Object.assign(addedElements, { [index]: changedElement });
                } else Object.assign(addedElements, { [index]: changedElement });
            }
            break;
        }
    }
}
```

You see? Very ugly...
If there would be an argumentslist passed to the listener, this would be much easyer =)
I am using this lib together with two-way-data-binding and I want to notify the components what happened to the data. So I have to determine which element was added to the array and which was removed from. I Could use something like diff-object-deep, but this is not exactly what I am searching for because it would say that an element was updated when the first element was deleted and another element takes its place

**Comment by DarrenPaulWright** [comment]
I'm sorry this has taken so long. I'm planning to include this in a 3.0 release in the near future. My plan is to change the fourth parameter to an object with method info, so name, arguments, and return value. 

I'm also using this library in a similar way, as you are and I'm planning an option where you can turn on sub changes in specific methods. For instance, you could get individual onChange callbacks when changes are made within a forEach call instead of rolling them up into one callback. Have you thought of any other features that would be helpful that I could include?

**Comment by Eluminati** [comment]
Hmm, not sure. It depends on how you are planning to implement this. I am imagining this now something like that:

```javascript
onChange(object, (path, value, previousValue, name) => {
    // Do general stuff here
},
{
    // More explicit stuff here
    push: (args) => {},
    pop: () => {},
    assign: () => {},
    // And so on
});
```

**Comment by DarrenPaulWright** [comment]
no, the method info would be more like this:
```javascript
onChange(object, (path, value, previousValue, methodInfo) => {
    console.log(methodInfo.name);
    console.log(methodInfo.arguments);
    console.log(methodInfo.returnValue);
});
```

and the new option would be like this:

```javascript
onChange(object, () => {
    // this is called for every change within the forEach and map methods.
}, {
    details: ['forEach', 'map']
);
```

**Comment by Eluminati** [comment]
Ah OK. Much better than my Idea. and 

```javascript
{
    details: true
}
```

would enable this for every method?

Another Idea which comes to me last night is, that "isShallow" should be a depth, for example

```javascript
const myObject = {
    depth0: {
        depth1: {
            depth2: {
                depth3: "change wont be detected"
            },
            depth21: "change will be detected"
        },
        depth11: "change will be detected"
    },
    depth01: "change will be detected"
};

onChange(myObject, callback, {
    isShallow: 2 // same behavior as "isShalllow: true" but only since depth 2
});
```

is this possible? Maybe it should be renamed to "watchDepth" or something like that.

**Comment by DarrenPaulWright** [comment]
I was able to get all these improvements in to 3.0.0 except watchDepth, as it presented some issues I need to mull over. Sorry it took me so long, life has been crazy.
