### ISSUE TITLE
Able to use in a Vanilla JS environment

### ISSUE THREAD

**Issue by DanielIndie95** [sindresorhus/on-change#64]
I Would like to upload this package to a cdn of a sort, but for that to be possible it is needed to purely js (without require and such. Is there a way to sort of "bundle it" so it would be accessible through Vanilla js and therefore upload-able to a cdn?

**Comment by sindresorhus** [comment]
I think you might be able to use https://wzrd.in/, but that's really something you need to figure out yourself. Alternatively, run Browserify locally.
