### ISSUE TITLE
Incompatible receiver error with Set/Map

### ISSUE THREAD

**Issue by hpx7** [sindresorhus/on-change#67]
Repro:
```
const foo = { x: new Set() };
const bar = onChange(foo, () => {});
console.log(bar.x.has("baz")); // => TypeError: Method Set.prototype.has called on incompatible receiver [object Object]
```

Same things happens with Map as well

**Comment by hpx7** [comment]
@DarrenPaulWright have you been able to repro this on your end?

**Comment by DarrenPaulWright** [comment]
Yes, I have, and I have the fix mostly done. I hope to wrap up a few loose ends this weekend.

**Comment by DarrenPaulWright** [comment]
Fixed in [v2.1.4](https://github.com/sindresorhus/on-change/releases/tag/v2.1.4)

**Comment by hpx7** [comment]
@DarrenPaulWright fyi this seems to have regressed in 2.2.0+
```
/project/node_modules/on-change/index.js:150
                                const result = Reflect.apply(
                           ^
TypeError: Method Map.prototype.entries called on incompatible receiver [object Object]
    at Proxy.entries (<anonymous>)
    at Object.apply (/project/node_modules/on-change/index.js:150:28)
```

**Comment by DarrenPaulWright** [comment]
Most methods for Maps and Sets still work, but I failed to test iterators. I've created a new issue to track this (#72)
