### ISSUE TITLE
Improve array handling

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/on-change#7]
It works fine, but could be optimized. There are certain actions that cause many `onChange()` calls even though only one is desirable.

- `array.pop()` causes two calls. One to delete the element and one to `defineProperty` the new `.length`. This could be made into one `onChange()` call. Same with `.unshift()`, `.shift()`, `.push()` too.
- `array.sort()` causes a call for each time it moves an element. Here too we're only interested in one call. Same applies to `.reverse()`, and probably `.splice()` too.

**Comment by sorodrigo** [comment]
For the first case, what if the call to onChange gets memoized with the object entries as a key?

For the second case this wouldn’t really work cause every time an element position changes the key would change.

**Comment by sorodrigo** [comment]
Hey I know you're probably super busy. Just wanted to ping you to know if you've had the chance to have a look at #8 . Thanks! @sindresorhus
