### ISSUE TITLE
proxy is revoked when proxy is assigned to itself even when the property is ignored

### ISSUE THREAD

**Issue by Eluminati** [sindresorhus/on-change#75]
Hi again,

when I have a model, let's call ist ActiveUser, which is wrapped into a proxy with on-change and with a property "editingModel" which is an ignored key, the Proxy of ActiveUser on the property "editingModel" will be revoked when ActiveUser is assigned to editingModel.

Example:

```javascript

// Expected
Proxy(ActiveUser {
    editingModel: Proxy(ActiveUser{}), // This is an ignored key which should be able to hold the same proxy
    anotherProperty: ...
})

// Currently
Proxy(ActiveUser{
    editingModel: ActiveUser{}, // Same Object as the Proxy target but not a proxy anymore
    anotherProperty: ...
})
```

I understand why this behavior of revoking the proxy when it is assigned to itself exists, but is it necessarry to have this behavior on ignored keys or keys which are not wraped into a proxy?

Sure you want to avoid loops but I think on-change schould be able to deal with circular structures without removing proxies.
Currently this makes my bachelor thesis a little bit mor complicated. ;)

**Comment by DarrenPaulWright** [comment]
Is the ActiveUser assigned to editingModel a reference to the same ActiveUser that editingModel is part of? A working code sample would be helpful.

**Comment by Eluminati** [comment]
Sorry I totally forgot thus. I solved it now by just checking if the model in the editingModel property is the same instance as the "owner". When yes I select the model directly from the store and otherwise I choose the editingModel.

Assigning the unproxied model is not an option because I have to check for changes.

Btw. Maybe I forgot to mention that the model instance on the editingModel is exactly the same instance as the wrapping object. So ActiveUser is assigned to itself. That's why an recursion occurres and I know that you added so code to avoid that when calling the changeCallback
