### ISSUE TITLE
Changes not detected on internal variables

### ISSUE THREAD

**Issue by hpx7** [sindresorhus/on-change#78]
I'm using the popular https://github.com/jhlywa/chess.js but can't seem detect changes on mutations of the Chess object

Repro:
```js
import onChange from "on-change";
import { Chess } from "chess.js";

const chess = new Chess();
const watchedChess = onChange(chess, () => {
  console.log("change detected");
});

watchedChess.foo = "bar"; // change detected
watchedChess.move({ from: "e2", to: "e4" }); // no change detected, even though this function mutates internal state
```

I suspect the issue is related to the [internal chess state representation](https://github.com/jhlywa/chess.js/blob/master/chess.js#L153-L162), which is not exposed to library consumers. Do you see any way/workaround to make this work?

**Comment by DarrenPaulWright** [comment]
You are correct, they are storing moves in a private var, so on-change can't see those changes. I recommend two possibilities:
1. Extend chess.js and wrap all mutable methods to trigger a change event.
2. Add an onChange method to the library that triggers an event whenever a change is detected.

I don't think you would need this library for either of those options.
