### ISSUE TITLE
Feature request: support async calls on validate and / or on change

### ISSUE THREAD

**Issue by Eluminati** [sindresorhus/on-change#80]
Hi again,

yesturday I had to check for validation in an async way before assigning the value. Do you think it is possible to add async support to the whole library? I think it would be necessary to add a queue for each property on each object and proxy because while validating the value can change again and then the order of changes can be corrupted. It is not just for possible http fetches but also for performance reasons. It is not a must have but would be very nice since JS is optimized for async programming.

**Comment by DarrenPaulWright** [comment]
I think I'll need a code sample of this. This sounds like something we may be able to solve outside of the library.

**Comment by Eluminati** [comment]
the example could something like this:

```javascript
onChange(array, (path, value, prev) => {
    // On change stuff here
}, {
    onValidate: async (...args) => {
        const result = await lib.doExpensiveValueCheckInWebWorker(...args);
        if (result instanceof Error) return false;
        return true
    }
})
```

May be let the expensive value check a check of a schema for example a mongoose schema check on client side.
Depending on the size of the schema, this can take much resources and the browser would freeze.

**Comment by DarrenPaulWright** [comment]
I agree with Sindre on this. You'll need to add a queue and async functionality within the callbacks.
