### ISSUE TITLE
What are breaking changes in version 3

### ISSUE THREAD

**Issue by lroal** [sindresorhus/on-change#81]
Hello.
I was just wondering what is the breaking changes moving from 2 to 3 ?
I can see that it v3  supports only node >=10 according to package.json.
Is there any specific reason ? Will it crash in node 8 ?

**Comment by DarrenPaulWright** [comment]
The last parameter provided in the callback changed from a string of the name of the method called to an object with name of the method, the args provided to the method, and the result value.
