### ISSUE TITLE
Convert to ES6 module syntax

### ISSUE THREAD

**Issue by DarrenPaulWright** [sindresorhus/on-change#85]
@sindresorhus I've noticed that many of your libraries are moving to ES6 module syntax and bumping the supported node version to 12. I'm happy to do that conversion here as well. Is there another library/commit you could point me to that has done the conversion already so I don't miss anything important? Or, other than the main code conversion and adding "type": "module" to package.json, is there anything else I should be aware of?

**Comment by sindresorhus** [comment]
I can do the conversion. It's easier for me to just do it quickly than to review a PR. I'll do it tonight.

**Comment by sindresorhus** [comment]
I did the conversion in https://github.com/sindresorhus/on-change/commit/e3fea2621cf6a6f38e9089746391596df4c3c71c. Unfortunately, it caused some test failures I could not figure out...

**Comment by DarrenPaulWright** [comment]
Thanks, I'll take a look.
