### ISSUE TITLE
Slow down major releases

### ISSUE THREAD

**Issue by lroal** [sindresorhus/on-change#86]
I see that you are already have relased v.4.0.0.
Take a look at the download stats at npm you will see that most users are still on version 2.
Downloads the last 7 days:
4..0.0.........221
3.0.2.........978
2.2.3.........9172
So I think it would be nice if new features also be added to version 2. E.g. the onValidate callback.
Users and vendor libraries are not able to keep up with the pace of you major releases.
I really think you should slow down major releases and try to make it backwards compatible. You are also making it hard for other library vendors that wants to support older versions of node.

**Comment by sindresorhus** [comment]
Supporting multiple release lines and backporting is just too much effort, unless you're offering to do the work?

**Comment by sindresorhus** [comment]
I can understand some projects cannot upgrade to v4 yet, but what's stopping you from upgrading to v3?

**Comment by sindresorhus** [comment]
@DarrenPaulWright In https://github.com/sindresorhus/on-change/releases/tag/v3.0.0, it's not clear what are the breaking changes requiring the major bump. Would you be able to mark which of the changes are the breaking changes?

**Comment by sindresorhus** [comment]
> You are also making it hard for other library vendors that wants to support older versions of node.

We, like most of the npm ecosystem, support the oldest supported version LTS of Node.js, which at the moment is Node.js 12. We have no plans to support Node.js versions that the Node.js core team doesn't even support.

**Comment by lroal** [comment]
Yes, I understand it requires a lot of effort. Maybe I will look into some of the methods and see if it is possible to backport them.
Side note: I am a open source author myself, and I am trying to keep some of the libs compatible with older versions of node (even 8 and 10) because I know some of the consumers are not able to upgrade node in near future due to difference reasons.

Still, I think  the high number of consumers on version 2.2.3 is a bit worrying. When you have x numbers of dependencies in package.json, (and on-change is only of of them), it is hard to keep an eye of the major versions.

**Comment by sindresorhus** [comment]
> and I am trying to keep some of the libs compatible with older versions of node (even 8 and 10) because I know some of the consumers are not able to upgrade node in near future due to difference reasons.

Honestly, that seems like wasted time you could have spent on fixing bugs and doing more important tasks. The convention in the community is to target the oldest supported LTS of Node.js. As a package author, it makes no sense to support Node.js versions that not even the Node.js team supports. If there are some users that cannot upgrade Node.js versions for some reasons, they can just stay on an older version.

> Still, I think the high number of consumers on version 2.2.3 is a bit worrying.

I don't think the number mean much. You cannot know the reason for it. Some projects might just not actively update dependencies and that's fine.

**Comment by lroal** [comment]
I understand, thank's for your time. I am closing this issue now.
