### ISSUE TITLE
Protection against non-writable/non-configurable properties

### ISSUE THREAD

**Issue by djfdev** [sindresorhus/on-change#9]
For more context, see [my question on SO](https://stackoverflow.com/questions/48494674/calling-concat-on-proxied-array-throws-error).

**Problem:**

Some methods catch the `get` trap when trying to look up non-configurable and/or non-writable properties (for instance, `Array#concat`). This breaks because the returned value from a property lookup violates the first [proxy object invariant](https://www.ecma-international.org/ecma-262/8.0/#sec-proxy-object-internal-methods-and-internal-slots-get-p-receiver):

> The value reported for a property must be the same as the value of the corresponding target object property if the target object property is a non-writable, non-configurable own data property.

My cursory understanding of this means that the `prototype` returned by the proxied object does not match that of the original object, so it breaks this rule.

**Steps to reproduce:**

I don't know *every* method this fails for, but if you use any of the "functional" array methods on a property of something wrapped in `on-change`, you'll see the error. These methods fail when looking up the target's `prototype`.

```js
const onChange = require('on-change')

const proxy = onChange({ items: ['foo', 'bar'] }, () => {
  console.log('changed')
})

proxy.items = proxy.items.concat('baz')

/*
  TypeError: 'get' on proxy: property 'prototype' is a read-only and non-configurable data property
  on the proxy target but the proxy did not return its actual value (expected '[object Array]' but got
  '[object Object]')
*/
```

**(Potential) solution:**

Add a check to see if the property descriptor is configurable and writable, and if not, return an unwrapped version of the property:

```js
get (target, property, receiver) {
  const desc = Object.getOwnPropertyDescriptor(target, property)
  const value = Reflect.get(target, property, receiver)

  if (desc && !desc.writable && !desc.configurable) return value

  try {
    return new Proxy(target[property], handler)
  } catch (error) {
    return value
  }
}
```

**Comment by goelayu** [comment]
The above solution doesn't work if the property is of the type function, because then it would lead to an illegal invocation error due to an incorrect context. 
```
var p = new Proxy(window, handler)
p.location.valueOf() // throws illegal invocation error since valueOf is a non configurable and non writable property and you don't intercept the method call

```

**Comment by sindresorhus** [comment]
@kpruden Did #16 fix this?

**Comment by kpruden** [comment]
Yes, I think so..
