### ISSUE TITLE
[browser] Array.prototype.forEach() / .map() do not work

### ISSUE THREAD

**Issue by friedow** [sindresorhus/on-change#94]
Most of the Array.protoype functions which iterate over the array like `Array.prototype.forEach()` or `Array.prototype.forEach()` do not work on the proxied objects.

Minimal not working example:
``` js
const proxiedArray = onChange(["should be logged"], () => { /* is not needed for this example */ });
proxiedArray.forEach((arrayElement) => console.log(arrayElement)); // does not log the string contained in the array
```

The problem is that the `Array.prototype` functions only execute their callback after checking the existance of an array element using `Object.HasProperty`. Since the `has` handler is not implemented, this check always fails. The problem and its solution is described in detail in https://stackoverflow.com/a/40408918.

BTW: I'm already working on this in my fork. Expecting to open a PR to fix this tomorrow!

**Comment by friedow** [comment]
The whole thing seems to be a browser-only issue. The example code given above works when executed in node.js but not when executed in chrome.

**Comment by DarrenPaulWright** [comment]
I am currently using on-change in another library on an array, and the tests for forEach and all the other iterators all pass in chrome and firefox. Have you tested this issue in a browser?

**Comment by DarrenPaulWright** [comment]
I just tried your exact code sample in chrome and firefox and it worked correctly.
